/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Cashier } from "./Cashier";
import { CashierCountArgs } from "./CashierCountArgs";
import { CashierFindManyArgs } from "./CashierFindManyArgs";
import { CashierFindUniqueArgs } from "./CashierFindUniqueArgs";
import { CreateCashierArgs } from "./CreateCashierArgs";
import { UpdateCashierArgs } from "./UpdateCashierArgs";
import { DeleteCashierArgs } from "./DeleteCashierArgs";
import { CashierService } from "../cashier.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Cashier)
export class CashierResolverBase {
  constructor(
    protected readonly service: CashierService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Cashier",
    action: "read",
    possession: "any",
  })
  async _cashiersMeta(
    @graphql.Args() args: CashierCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Cashier])
  @nestAccessControl.UseRoles({
    resource: "Cashier",
    action: "read",
    possession: "any",
  })
  async cashiers(
    @graphql.Args() args: CashierFindManyArgs
  ): Promise<Cashier[]> {
    return this.service.cashiers(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Cashier, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Cashier",
    action: "read",
    possession: "own",
  })
  async cashier(
    @graphql.Args() args: CashierFindUniqueArgs
  ): Promise<Cashier | null> {
    const result = await this.service.cashier(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Cashier)
  @nestAccessControl.UseRoles({
    resource: "Cashier",
    action: "create",
    possession: "any",
  })
  async createCashier(
    @graphql.Args() args: CreateCashierArgs
  ): Promise<Cashier> {
    return await this.service.createCashier({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Cashier)
  @nestAccessControl.UseRoles({
    resource: "Cashier",
    action: "update",
    possession: "any",
  })
  async updateCashier(
    @graphql.Args() args: UpdateCashierArgs
  ): Promise<Cashier | null> {
    try {
      return await this.service.updateCashier({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Cashier)
  @nestAccessControl.UseRoles({
    resource: "Cashier",
    action: "delete",
    possession: "any",
  })
  async deleteCashier(
    @graphql.Args() args: DeleteCashierArgs
  ): Promise<Cashier | null> {
    try {
      return await this.service.deleteCashier(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
